INSERT INTO VEHICLE (id, name, REGISTRATION_NUMBER) VALUES (1, 'Car 1', 'AB12 CDE');
INSERT INTO VEHICLE (id, name, REGISTRATION_NUMBER) VALUES (2, 'Car 2', 'CD23 FGH');
INSERT INTO VEHICLE (id, name, REGISTRATION_NUMBER) VALUES (3, 'Car 3', 'EF34 IJK');

INSERT INTO RFID_TAG(id, VEHICLE_ID) VALUES (1, 2);
INSERT INTO RFID_TAG(id, VEHICLE_ID) VALUES (2, 3);
INSERT INTO RFID_TAG(id, VEHICLE_ID) VALUES (3, 1);

INSERT INTO CUSTOMER(id, name, RFID_TAG_ID) VALUES (1, 'Customer 1', 1);
INSERT INTO CUSTOMER(id, name, RFID_TAG_ID) VALUES (2, 'Customer 2', 2);
INSERT INTO CUSTOMER(id, name, RFID_TAG_ID) VALUES (3, 'Customer 3', 3);

INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (1, '1A2B', '1');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (2, '1A2B', '2');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (3, '1A2B', '3');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (4, '2B3C', '1');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (5, '2B3C', '2');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (6, '3C4D', '1');