INSERT INTO RFID_TAG(id, REGISTRATION_NUMBER) VALUES (1, 'AB12 CDE');
INSERT INTO RFID_TAG(id, REGISTRATION_NUMBER) VALUES (2, 'CD23 FGH');
INSERT INTO RFID_TAG(id, REGISTRATION_NUMBER) VALUES (3, 'EF34 IJK');

INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (1, '1A2B', '1');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (2, '1A2B', '2');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (3, '1A2B', '3');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (4, '2B3C', '1');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (5, '2B3C', '2');
INSERT INTO CHARGE_POINT(id, UNIQUE_SERIAL_NUMBER, CONNECTOR_NUMBER) VALUES (6, '3C4D', '1');

INSERT INTO CHARGING_SESSION(CHARGEPOINT_ID, STARTDATE, ENDDATE, INITIALMETER_VALUE, FINALMETER_VALUE)
VALUES (1, '2023-03-01 10:31', '2023-03-01 17:02', '5', '10');